name: course_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_auth_web: ^6.1.0
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_storage_web: ^3.8.0

  google_fonts: ^6.3.2
  persistent_bottom_nav_bar: ^6.2.1

  iconly: ^1.0.1
  ionicons: ^0.2.2
  flutter_svg: ^2.2.2
  percent_indicator: ^4.2.5
  otp_text_field: ^1.1.3

  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.0
  flutter_pdfview: ^1.4.3

  flutter_dotenv: ^5.0.2
  http: ^1.1.0

  url_launcher: ^6.2.5
  video_player: ^2.8.2
  animations: ^2.0.8
  youtube_player_iframe: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/svg/
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 300
